# Generated by Django 3.1.3 on 2020-12-02 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='name')),
                ('birthdate', models.DateTimeField(null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this user has verified email. ', verbose_name='email verification status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='DropoutReasonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(help_text='탈회 사유 구분 기준 명칭', max_length=200, verbose_name='name')),
            ],
            options={
                'db_table': 'dropout_reason_category',
            },
        ),
        migrations.CreateModel(
            name='SignupRouteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(help_text='가입 경로 구분 기준 명칭', max_length=200, verbose_name='name')),
            ],
            options={
                'db_table': 'signup_route_category',
            },
        ),
        migrations.CreateModel(
            name='UserRouteMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('comment', models.CharField(help_text='좀 더 상세한 가입경로 설명', max_length=200, verbose_name='comment')),
                ('category', models.ForeignKey(help_text='가입 경로 구분 기준 명칭', on_delete=django.db.models.deletion.CASCADE, to='core.signuproutecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_route_map',
            },
        ),
        migrations.CreateModel(
            name='UserDropoutReasonMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('comment', models.CharField(help_text='좀 더 상세한 탈회사유 설명', max_length=200, verbose_name='comment')),
                ('category', models.ForeignKey(help_text='탈회 사유 구분 기준 명칭', on_delete=django.db.models.deletion.CASCADE, to='core.dropoutreasoncategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropout_reasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_dropout_reason_map',
            },
        ),
    ]
