# Generated by Django 3.1.3 on 2020-12-02 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('alias', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(max_length=40)),
                ('bank_code', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('alias', models.CharField(blank=True, max_length=200)),
                ('account_started', models.DateTimeField(null=True)),
                ('balance_started', models.IntegerField(default=0)),
                ('bankruptcy_balance', models.IntegerField(default=-1)),
                ('accounts', models.ManyToManyField(blank=True, to='core.BankAccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledgers',
            },
        ),
        migrations.CreateModel(
            name='LedgerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('inout_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=4)),
                ('connected_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ledgercategory')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ledger')),
            ],
            options={
                'db_table': 'ledger_categories',
            },
        ),
        migrations.CreateModel(
            name='LedgerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('application_date', models.DateTimeField()),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('inflow', models.IntegerField(default=0)),
                ('outflow', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ledgercategory')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ledger')),
            ],
            options={
                'db_table': 'ledger_records',
            },
        ),
        migrations.CreateModel(
            name='LedgerMonthlyExpectedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField(null=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('inflow', models.IntegerField(default=0)),
                ('outflow', models.IntegerField(default=0)),
                ('date_of_month', models.IntegerField()),
                ('allow_weekend', models.BooleanField(default=False)),
                ('on_weekend_postpone', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ledgercategory')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ledger')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ledgermonthlyexpecteditem')),
            ],
            options={
                'db_table': 'ledger_monthly_expected_items',
            },
        ),
        migrations.CreateModel(
            name='LedgerExpectedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('application_date', models.DateTimeField()),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('inflow', models.IntegerField(default=0)),
                ('outflow', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ledgercategory')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ledger')),
            ],
            options={
                'db_table': 'ledger_expected_records',
            },
        ),
        migrations.CreateModel(
            name='BankAccountTransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.CharField(blank=True, max_length=200)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_type', models.CharField(blank=True, max_length=20)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('inflow', models.IntegerField(default=0)),
                ('outflow', models.IntegerField(default=0)),
                ('after_balance_amount', models.IntegerField()),
                ('branch_name', models.CharField(blank=True, max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bankaccount')),
            ],
            options={
                'db_table': 'bank_account_transaction_records',
            },
        ),
    ]
